[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  API_BASE_URL = "https://api.guzellestir.com"

# API routes için Netlify Functions
[[redirects]]
  from = "/api/subdomains/validate/*"
  to = "/.netlify/functions/subdomain-validate"
  status = 200

# Frontend routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Subdomain routing
[[redirects]]
  from = "https://:subdomain.guzellestir.com/*"
  to = "/menu"
  status = 200
  force = true
  conditions = {
    subdomain = ["kardesler", "lezzet-duragi", "cafe-corner", "bistro-34", "demo", "example", "test", "pizzapalace", "burgerking", "sushimaster", "coffeecorner", "steakhouse"]
  }
