[build]
  publish = "out"
  command = "npm run build"

[[redirects]]
  from = "https://admin.guzellestir.com/*"
  to = "/admin/:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://*.guzellestir.com/business/*"
  to = "/business/:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://*.guzellestir.com/kitchen/*"
  to = "/kitchen/:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://*.guzellestir.com/*"
  to = "/business/dashboard"
  status = 200
  force = true

[[redirects]]
  from = "https://guzellestir.com/*"
  to = "/admin/:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://www.guzellestir.com/*"
  to = "/admin/:splat"
  status = 200
  force = true

# Fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200