# Admin subdomain için Netlify yapılandırması
[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"

# Admin subdomain routing
[[redirects]]
  from = "/"
  to = "/admin/login"
  status = 302
  force = true
  conditions = {Host = "admin.guzellestir.com"}

[[redirects]]
  from = "/admin"
  to = "/admin/login"
  status = 302
  force = true
  conditions = {Host = "admin.guzellestir.com"}

# Ana domain'den admin erişimini engelle
[[redirects]]
  from = "/admin/*"
  to = "https://admin.guzellestir.com/admin/:splat"
  status = 301
  force = true
  conditions = {Host = "guzellestir.com"}

# HTTPS zorunluluğu
[[headers]]
  for = "https://admin.guzellestir.com/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self'; connect-src 'self'; frame-ancestors 'none';"

# Admin sayfalarına sadece HTTPS ile erişim
[[redirects]]
  from = "http://admin.guzellestir.com/*"
  to = "https://admin.guzellestir.com/:splat"
  status = 301
  force = true

# Ana siteyi admin subdomain'den koru
[[redirects]]
  from = "https://guzellestir.com/admin/*"
  to = "https://admin.guzellestir.com/:splat"
  status = 301
  force = true

# Güvenlik için admin klasörüne doğrudan erişimi engelle
[[redirects]]
  from = "/admin/*"
  to = "/404"
  status = 404
  conditions = {Host = "guzellestir.com"}

# Rate limiting (Netlify Functions ile)
[functions]
  directory = "netlify/functions"

# Admin API'leri için özel yapılandırma
[[redirects]]
  from = "https://admin.guzellestir.com/api/admin/*"
  to = "/api/admin/:splat"
  status = 200
