[build]
  command = "npm run build && npm run export"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  API_BASE_URL = "https://api.guzellestir.com"

# API routes için Netlify Functions
[[redirects]]
  from = "/api/subdomains/validate/*"
  to = "/.netlify/functions/subdomain-validate"
  status = 200

# Frontend routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Subdomain routing için edge function
[[edge_functions]]
  function = "subdomain-router"
  path = "/*"

# Admin routing için edge function  
[[edge_functions]]
  function = "admin-router"
  path = "/admin/*"